# Generated by Django 5.2.8 on 2025-12-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
